name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GCP via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 34.22.192.120
          username: reg-gordon1977
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd /var/www/html/ecommerce-test
            git pull origin main
            sudo systemctl restart apache2
